import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/Header/Header"
import Footer from "@/components/Footer/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header />
      <body
        className={inter.className}
        style={{
          marginTop: 100,
          // height: 2000,
          display: "flex",
          justifyContent: "center",
        }}
      >
        <div style={{ height: "100%", width: "100%", maxWidth: "1440px" }}>
          {children}
        </div>
      </body>
      <Footer />
    </html>
  )
}
